import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rainbowkit - Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-10 py-5">
        <header className="flex justify-between items-center">
          <h1 className="text-3xl font-bold">Logo Here</h1>
          <ConnectButton />
        </header>
      </main>
    </>
  );
}
